openapi: 3.0.0
info:
  version: 1.0
  title: >-
    algemeen
  description: >-
    
  contact:
    name: GGM Team
    email: ggm@kvk.nl
paths: {}
components:
  schemas:


    # Land representatie
    Land:
      description: >-
        Een land is een gebied, afgebakend door middel van grenzen, waar een zelfstandige regering de scepter zwaait. De Kamer van Koophandel beheert haar eigen lijst met landen. Deze lijst is gebaseerd op de landenlijst van de GBA en ISO-Landen.
        
      required:
        - naam of code?
        - toegangsnummer
      properties:
        naam of code?:
          type: string of int
        toegangsnummer:
          description: >-
            Het land-toegangsnummer voor telefonie.
Bijv. +32 of 0032 voor België of +44 voor Verenigd Koninkrijk.
          type: string
        telecomnummer:
          $ref: '#/components/schemas/Telecomnummer'


    # Naamrelatie representatie
    Naamrelatie:
      description: >-
        
      required:
        - naam
      allOf:
        - $ref: 'meta_v1.yaml#/components/schemas/MaterieleRelatie'
        - properties:
            naam:
              $ref: '#/components/schemas/Naam'


    # RechtspersoonOfOnderneming representatie
    RechtspersoonOfOnderneming:
      description: >-
        De referentie naar een rechtspersoon of een onderneming. plus de (afgeleide) naam van de rechtspersoon of de onderneming.
      required:
        - type
        - naam
      properties:
        type:
          type: string
          enum:
            - Rechtspersoon
            - Onderneming
        naam:
          type: string
        persoonsnummer:
          description: >-
            Het persoonsnummer in het geval van een rechtspersoon.
          type: string
          format: UUID
        kvkNummer:
          description: >-
            <ul>
          	<li>Het KVK-nummer van de onderneming (en de rechtspersoon die de onderneming drijft) in het geval van een onderneming of</li>
          	<li>het KVK-nummer van de maatschappelijke activiteit van de rechtspersoon.</li>
          </ul>
          type: string
          format: Numeriek8


    # VolgordelijkeNaamrelatie representatie
    VolgordelijkeNaamrelatie:
      description: >-
        
      required:
        - naam
      allOf:
        - $ref: 'meta_v1.yaml#/components/schemas/VolgordelijkeMaterieleRelatie'
        - properties:
            naam:
              $ref: '#/components/schemas/Naam'


    # Naam representatie
    Naam:
      description: >-
        De naam van de maatschappelijke activiteit, vestiging of rechtspersoon.
N.B. de naam wordt alleen gebruikt onder de volgende voorwaarden:
        <ul>
        	<li>voor een MA indien de MA niet in een onderneming wordt uitgeoefend. In dat geval worden er één of meer handelsnamen vastgelegd.</li>
        	<li>voor een vestiging alleen indien deze de vestiging van een MA is. Voor een vestiging van een onderneming worden er één of meer handelsnamen vastgelegd.</li>
        </ul>
<i>HR 2009: De naamgeving van een rechtspersoon, samenwerkingsverband of niet-commerciële vestiging.</i>
      required:
        - administratieveNaam
        - naam
        - verkorteNaam
        - ookGenoemd
      properties:
        administratieveNaam:
          description: >-
            <i>Afgeleid.</i>
          De administratieve naam in het handelsregister. Dit is de verkorte naam of de volledige naam indien er geen verkorte naam is vastgelegd.
          type: 
        naam:
          description: >-
            De volledige naam.
          type: 
        verkorteNaam:
          description: >-
            De 'verkorte naam' is de administratieve naam in het handelsregister indien de (gehele) 'naam' langer is dan 45 karakters.
          
          type: 
        ookGenoemd:
          description: >-
            Een andere naam waaronder de maatschappelijk activiteit, rechtspersoon of vestiging ook bekend is.
          type: 


    # Communicatiegegevens representatie
    Communicatiegegevens:
      description: >-
        Een set aan communicatiegegevens zijnde één of meer van de volgende gegevens:
        <ul>
        	<li>(inter)nationaal telefoonnummer of faxnummer</li>
        	<li>internet-domeinnaam</li>
        	<li>emailadres</li>
        	<li>berichtenbox</li>
        </ul>
      properties:
        domeinnaam:
          description: >-
            Een lijst domeinnamen.
          type: array
          items:
            $ref: '#/components/schemas/Domeinnaam'
        emailadres:
          description: >-
            Een lijst emailadressen.
          type: array
          items:
            $ref: '#/components/schemas/Emailadres'
        telecomnummer:
          description: >-
            Een lijst met telecomnummers.
          type: array
          items:
            $ref: '#/components/schemas/Telecomnummer'
        berichtenbox:
          $ref: '#/components/schemas/Berichtenbox'


    # Activiteitenomschrijving representatie
    Activiteitenomschrijving:
      description: >-
        De activiteitenomschrijving is de omschrijving van de activiteiten die worden uitgeoefend op de vestiging of rechtspersoon. Dit kan zowel de bedrijfsomschrijving zijn als een doelomschrijving van de rechtspersoon (vereniging/stichting/VvE/kerkgenootschap). Voor een vestiging is dit een korte omschrijving van de activiteiten van de betreffende vestiging.
      required:
        - tekst
      allOf:
        - $ref: 'gebeurtenis_v1.yaml#/components/schemas/FormeelObject'
        - properties:
            tekst:
              description: >-
                De omschrijving.
              type: 


    # Telecomnummer representatie
    Telecomnummer:
      description: >-
        Een telecomnummer is ofwel een Telefoonnummer, ofwel een Faxnummer, en is het nummer zonder het toegangsnummer van het land, waarbinnen het nummer geldig is.
        Het land wordt aangegeven met een referentie.
      required:
        - nummer
        - telecomtype
      allOf:
        - $ref: 'gebeurtenis_v1.yaml#/components/schemas/MaterieelObject'
        - properties:
            nummer:
              type: string {Telefoonnummer}
            telecomtype:
              type: string


    # Domeinnaam representatie
    Domeinnaam:
      description: >-
        De domeinnaam is de naam (of namen) waaronder de onderneming zaken doet of informatie verschaft op het internet.
      required:
        - naam
      allOf:
        - $ref: 'gebeurtenis_v1.yaml#/components/schemas/MaterieelObject'
        - properties:
            naam:
              description: >-
                De naam is en string met het pattern {url}.
              type: string {URL}


    # Berichtenbox representatie
    Berichtenbox:
      description: >-
        Een berichtenbox.
      required:
        - berichtenboxadres
      allOf:
        - $ref: 'gebeurtenis_v1.yaml#/components/schemas/MaterieelObject'
        - properties:
            berichtenboxadres:
              description: >-
                berichtenboxadres = &lt;berichtenboxnaam ondernemer&gt;@berichtenbox.antwoordvoorbedrijven.nl
Het adres mag geen spaties en hoofdletters bevatten. Het berichtenboxnaam gedeelte moet uit minimaal 4 en maximaal 45 karakters bestaan.
              type: string {Berichtenboxadres}


    # Emailadres representatie
    Emailadres:
      description: >-
        Een emailadres.
      required:
        - adres
      allOf:
        - $ref: 'gebeurtenis_v1.yaml#/components/schemas/MaterieelObject'
        - properties:
            adres:
              type: string {Emailadres}
